import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">LandingPage</Link>
        </li>
        <li>
          <Link to="/faqspage">FAQsPage</Link>
        </li>
        <li>
          <Link to="/signuppage">SignUpPage</Link>
        </li>
        <li>
          <Link to="/signinpage">SignInPage</Link>
        </li>
        <li>
          <Link to="/nftsmarketpage">NFTsMarketpage</Link>
        </li>
        <li>
          <Link to="/rewardspage">RewardsPage</Link>
        </li>
        <li>
          <Link to="/aboutuspage">AboutUsPage</Link>
        </li>
        <li>
          <Link to="/slide169one">Slide169One</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
